import type { Env } from "../../lib/env";
import { landBronzeObject, markBronzeProcessed } from "../../lib/bronze";
import {
  startPipelineRun,
  finishPipelineRun,
  isPipelinePaused,
  type TriggerType,
} from "../../lib/pipelineRuns";
import { logger } from "../../lib/logger";
import { runMetaQualityChecks } from "../../quality/run";
import { buildSiteSnapshot } from "./aggregate";
import { insertSiteEvent } from "./persist";
import type { SiteEventType } from "./types";

/**
 * Runs Pipeline 3's daily scheduled job: takes a snapshot of this Worker's
 * own operational state (pipeline run outcomes, quality check failures,
 * audit activity) and lands it exactly like any other bronze->silver
 * ingestion — the only difference from Pipelines 1/2 is that the "source"
 * being fetched is this D1 database itself, not a third-party API.
 */
export async function runMetaPipeline(
  env: Env,
  triggerType: TriggerType = "cron",
) {
  if (await isPipelinePaused(env, "meta")) {
    logger.info("meta pipeline is paused — skipping run", { pipeline: "meta" });
    return { skipped: true as const };
  }

  const runId = await startPipelineRun(env, "meta", triggerType);
  logger.info("meta pipeline run started", {
    pipeline: "meta",
    runId,
    triggerType,
  });

  try {
    const now = new Date();
    const since24h = new Date(
      now.getTime() - 24 * 60 * 60 * 1000,
    ).toISOString();

    const runRows = await env.DB.prepare(
      `SELECT pipeline, status FROM pipeline_runs`,
    ).all<{
      pipeline: string;
      status: string;
    }>();
    const failedQualityChecks = await env.DB.prepare(
      `SELECT COUNT(*) as n FROM data_quality_runs WHERE status = 'fail' AND run_at >= ?1`,
    )
      .bind(since24h)
      .first<{ n: number }>();
    const auditCount = await env.DB.prepare(
      `SELECT COUNT(*) as n FROM admin_audit_log`,
    ).first<{ n: number }>();
    const bronzeCount = await env.DB.prepare(
      `SELECT COUNT(*) as n FROM bronze_ingestion_log`,
    ).first<{
      n: number;
    }>();

    const snapshot = buildSiteSnapshot({
      generatedAt: now,
      runRows: runRows.results,
      qualityCheckFailures24h: failedQualityChecks?.n ?? 0,
      totalAuditActions: auditCount?.n ?? 0,
      bronzeObjectsTotal: bronzeCount?.n ?? 0,
    });

    const bronze = await landBronzeObject(env, {
      pipeline: "meta",
      kind: "analytics-snapshot",
      payload: snapshot,
      sourceUrl: "internal://d1-self-snapshot",
    });

    const silverId = await insertSiteEvent(env, {
      eventType: "analytics_snapshot",
      occurredAt: now.toISOString(),
      detail: snapshot,
      bronzeId: bronze.bronzeId,
    });
    await markBronzeProcessed(env, bronze.bronzeId);

    await runMetaQualityChecks(env, 1);

    await finishPipelineRun(env, runId, {
      status: "success",
      rowsBronze: 1,
      rowsSilver: 1,
      rowsGold: 0,
    });
    logger.info("meta pipeline run finished", {
      pipeline: "meta",
      runId,
      silverId,
    });

    return { skipped: false as const, runId, snapshot };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logger.error("meta pipeline run failed", {
      pipeline: "meta",
      runId,
      error: message,
    });
    await finishPipelineRun(env, runId, {
      status: "failed",
      errorDetail: message,
    });
    throw err;
  }
}

/**
 * Records one real deploy or build event, reported by CI right after it
 * actually happens (see routes/meta.ts for the webhook this backs) — not
 * generated by a schedule, since a day with no deploy genuinely has no
 * deploy event.
 */
export async function recordSiteEvent(
  env: Env,
  eventType: Extract<SiteEventType, "deploy" | "build">,
  detail: unknown,
): Promise<{ silverId: number; bronzeId: number }> {
  const now = new Date();
  const bronze = await landBronzeObject(env, {
    pipeline: "meta",
    kind: eventType,
    payload: detail,
    sourceUrl: "internal://ci-webhook",
  });
  const silverId = await insertSiteEvent(env, {
    eventType,
    occurredAt: now.toISOString(),
    detail,
    bronzeId: bronze.bronzeId,
  });
  await markBronzeProcessed(env, bronze.bronzeId);
  return { silverId, bronzeId: bronze.bronzeId };
}
